### ISSUE TITLE
Mismatch between `ts-rs`'s idea of `camelCase` and `serde`'s

### ISSUE THREAD

**Issue by alexschrod** [Aleph-Alpha/ts-rs#165]
I have a type like this:
```rs
#[derive(Debug, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ItemImageList {
    pub id: u32,
    pub crc32c_hash: u32,
}
```
The generated camelCase field name from `serde` for the field `crc32c_hash` is `crc32cHash`. `ts-rs`, on the other hand, decides to generate the following TS file:
```ts
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ItemImageList { id: number, crc32CHash: number, }
```

This obviously leads to problems when trying to use the `ItemImageList` interface in TS to read JSON serialized by serde.

The solution for me for the time being, has been to slap `#[ts(rename = "crc32cHash")]` on the field. But the question is, should there actually be a discrepancy here?

**Comment by NyxCode** [comment]
Thanks for opening the issue!
No, this is definetely not intentional. We use the `inflector` crate for converting between the inflection. Unfortunately, it seems like it isn't 100% compatible with serde. I suppose we need to figure it if we can directly use serde's logic for this conversion, or if has to be re-implemented.

**Comment by alexschrod** [comment]
Apparently this isn't the only crate being "hit" by this mismatch. https://github.com/whatisinternet/Inflector/issues/85
