### ISSUE TITLE
Feature request: `export_all_to_string` function

### ISSUE THREAD

**Issue by Blechlawine** [Aleph-Alpha/ts-rs#354]
`export_to_string` already does this, but only for one single type. `export_all_to_string` would basically do the same as `export_all` except output them as a `String` (Could also be a `Vec<String>`) to manually create the files for the types.

Currently, one can achieve the same result by manually calling `export_to_string()` on all types, manually searching for their dependencies, and calling `export_to_string()` on them as well.

**Comment by gustavo-shigueo** [comment]
The reason this is not supported is because of import paths. How would they be generated? Would it even make sense to generate them? If you `export_to_string` there is no guarantee that the file structure we expect will be maintained, so there is no reasonable way to implement `export_all_to_string` as the import paths would very quickly descend into chaos

**Comment by NyxCode** [comment]
If you really need something like this, you can iterate over all dependencies of a type recursively. See ts_rs/export for how that works.
