### ISSUE TITLE
Run outside of test context

### ISSUE THREAD

**Issue by thought2** [Aleph-Alpha/ts-rs#44]
I could not find a way to run the binding generation outside of a test context.

Personally I don't think running it as test is a good idea. I'd rather provide a CLI flag that runs the binding generation.

Anyways, I think it would make sense if this question is up to the user.

Or do I oversee something here?

**Comment by NyxCode** [comment]
While the actual binding can be obtained by calling `TS::decl`, the `export!` macro does a lot more, like generating imports.
I think it'd be great to have a 2nd macro, maybe `export_here!` or something like that, which does what `export!` does but in place instead of creating a `#[test]`.
I would happily accept a PR for that - all that would have to be done is to copy almost everything from `export!` into a new macro and then call it in `export!`.

**Comment by NyxCode** [comment]
resolved by #47
