### ISSUE TITLE
[Feature request] Generate strict typescript type with primitive newtype.

### ISSUE THREAD

**Issue by bokuweb** [Aleph-Alpha/ts-rs#50]
Hello, at first place I would like to thank you for your work.
I would like to generate a strict typescript type from a primitive newtype.

### Current behavior

``` rust 
#[derive(TS)]
pub struct FooId(usize);

#[derive(TS)]
pub struct BarId(usize);
```

The above rust code generates following typescript definition.

``` typescript
export type FooId = number;
export type BarId = number;
```

So, we can write following code without error.

``` typescript
const fooId: FooId = 0;
let barId: BarId = 1;

barId = fooId; // <- Ok
```

### Feature Request

I would like to generate following definitions.

``` typescript
type Phantom<T, U extends string> = T & { [key in U]: never };
export type FooId = Phantom<number, 'FooId'>;
export type BarId = Phantom<number, 'BarId'>;
```

With such a type, we can make the following assignments an error.
This is very useful if you want to strictly distinguish between ids.

``` typescript
const fooId: FooId = 0;
let barId: BarId = 1;

barId = fooId; // <- error
```

What do you think about it?

**Comment by NyxCode** [comment]
I like the idea, but this seems highly specialized to me, so not really something we can easily integrate in a general purpose binding generator.  
If you are passionate about this, feel free to give a PR a go. However, I think before implementing this the underlying code generation should be made much more flexible so that we don't end up with a lot of spaghetti code.
