### ISSUE TITLE
Support serde_json::Value

### ISSUE THREAD

**Issue by phayes** [Aleph-Alpha/ts-rs#63]
I have a few free-form values that I store as `serde_json::Value` types (they get stored as jsonb in my database). 

It would be nice to support `serde_json::Value`, I assume this would map to `any` on the typescript side.

**Comment by NyxCode** [comment]
Since this seems to be a pretty niche usecase, I wouldn't like to introduce another feature flag for this.  
However, you can always use `#[ts(type = "any")]` to manually override the TS type.

**Comment by daviareias** [comment]
This is how I solved it for me:
`// Use this fr using a generic type as any
#[derive( Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TsJsonValue(pub serde_json::Value);
impl TS for TsJsonValue {
    fn name() -> String {
        "any".into()
    }
    fn dependencies() -> Vec<ts_rs::Dependency> {
        vec![]
    }

    fn transparent() -> bool {
        true
    }
}



#[derive( Debug, Clone, PartialEq, Serialize, Deserialize, TS)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub struct ResponseData<T = TsJsonValue> {
    pub data: T,
    pub extensions: Option<Extensions>,
}`

**Comment by andrewbaxter** [comment]
`any` isn't a good solution because it could include unserializable things like functions, symbols, etc.

This doesn't seem like a niche feature to me, TS is explicitly a web language and the web today is full of JSON, and many APIs take freeform JSON (tags, metadata, payloads to forward to other blackbox systems, upstream data that isn't well defined, etc).

**Comment by andrewbaxter** [comment]
Ah! IIUC this was implemented, it requires feature `serde-json-impl`. Thanks!
