### ISSUE TITLE
Alternate representation for Option<T>

### ISSUE THREAD

**Issue by Roms1383** [Aleph-Alpha/ts-rs#8]
Hi, I've just tried out your crate on different definitions and it looks very promising !

There's just a question on how to alternatively handle `Option<T>` :

given this struct :
```rust
#[derive(Serialize, TS)]
struct CreateUser {
    first_name: Option<String>,
    last_name: Option<String>,
}
```
will currently generate :
```typescript
export interface CreateUser {
    first_name: string | null,
    last_name: string | null,
}
```
would it be possible to instead generate :
```typescript
export interface CreateUser {
    first_name?: string,
    last_name?: string,
}
```

I started looking at your lib sourcecode, but I might not have time to dig in, especially that I noticed on [impl<T: TS> TS for Option<T>](https://github.com/Aleph-Alpha/ts-rs/blob/8462b46362fcfddee6d20dd60c289152d194a6c6/ts-rs/src/lib.rs#L243) that it is currently implemented on the generated type, and I'm not sure how to link it with the generated field.

Any feedback would be greatly appreciated !
Thanks :)

**Comment by NyxCode** [comment]
Yes, this should be possible.  
It's currently implemented this way since this is [the default behaviour of serde](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1f77c84ce0e4b5c4b25c197d80e8f617).
However, as you corrently pointed out, the current implementation of `TS` doesn't allow for this.  

A possible solution would be to define a TSConfig struct
```rust
struct TSConfig {
    treat_option_as_optional: bool
}
```
which would be passed to `TS::name` and `TS::inline`.  

Then, the proc macro, which generates a `TS` implementation for your type, could parse a `#[ts(treat_option_as_optional)]` attribute and pass the according `TSConfig` instance to the calls.

Alternatively, this could just be solved by introducing a crate feature, and conditionally change the implementation of `TS for Option<T: TS>` depending of it, but I think it'd be nicer if this could be done on a per-struct and per-field basis.  

If you feel like it, you could give it a try - the code is not super complicated, and I'm always happy to help.

**Comment by Roms1383** [comment]
Thanks for your fast reply @NyxCode ! I actually agree with you about the implementation on a per-struct / per-field basis.

I would really like to give a try (never played with macro so far), I'll definitely get back to you but it's probably not gonna be soon since I'm quite busy at the moment.

**Comment by Roms1383** [comment]
Do you mean passing `treat_option_as_optional` directly to both `TS::name` and `TS::inline` or there's a way to retrieve it from inside the functions without adding an additional parameter ?

**Comment by NyxCode** [comment]
I thought about creating a struct like TSConfig and passing that to the functions.
That would make it easy to add additional attributes in the future.

**Comment by Roms1383** [comment]
Ah yes but when I was looking at it, it seems that it would have to be added in many many functions, am I correct?
I'd be up for a chat if you want!

**Comment by Roms1383** [comment]
p.s : I haven't yet pushed any changes on the fork because it's kinda messy at the moment (still logging stuff here and there to get familiar with your implementation and macro intricacies 😅)

**Comment by NyxCode** [comment]
sure, feel free to add me on discord. your ID is broken, i think the last digit is missing.

NyxCode#1137

**Comment by arendjr** [comment]
This is implemented in https://github.com/Aleph-Alpha/ts-rs/pull/19.
